# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-10 03:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Akun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis_akun', models.CharField(choices=[('farmer', 'Farmer'), ('admin', 'Admin'), ('surveyer', 'Surveyer'), ('quality', 'Quality')], max_length=20)),
                ('akun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pengguna',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=200)),
                ('full_name', models.CharField(blank=True, max_length=200)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('email', models.CharField(blank=True, max_length=200)),
                ('provinsi', models.CharField(blank=True, max_length=100)),
                ('kabupaten', models.CharField(blank=True, max_length=100)),
                ('kecamatan', models.CharField(blank=True, max_length=100)),
                ('alamat', models.CharField(blank=True, max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='akun',
            name='pengguna',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmer.Pengguna'),
        ),
    ]
