# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-10 04:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pengguna',
            name='alamat',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='pengguna',
            name='email',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='pengguna',
            name='full_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='pengguna',
            name='kabupaten',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pengguna',
            name='kecamatan',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pengguna',
            name='phone',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='pengguna',
            name='provinsi',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pengguna',
            name='username',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
