# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-15 04:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0002_auto_20170510_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='pengguna',
            name='photo',
            field=models.ImageField(blank=True, upload_to='users/%Y/%m/%d'),
        ),
    ]
