# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-16 13:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0005_auto_20170516_2027'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PengajuanLahan',
            new_name='Data_Pengajuan_Lahan',
        ),
    ]
