# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-16 14:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0006_auto_20170516_2029'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pengajuan_Gambar_Lahan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='pengajuanLahan/gambar')),
            ],
        ),
        migrations.AlterField(
            model_name='data_pengajuan_lahan',
            name='image_certificate',
            field=models.ImageField(blank=True, upload_to='pengajuanLahan/certificate'),
        ),
        migrations.AddField(
            model_name='pengajuan_gambar_lahan',
            name='lahan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmer.Data_Pengajuan_Lahan'),
        ),
    ]
