# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-17 01:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0008_auto_20170517_0835'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data_Pengajuan_Peminjaman',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=20, null=True)),
                ('besar_peminjaman', models.CharField(max_length=20, null=True)),
                ('alasan_peminjaman', models.TextField(null=True)),
                ('tanggal_peminjaman', models.DateTimeField(null=True)),
                ('status', models.CharField(max_length=20, null=True)),
                ('alasan_penolakan', models.TextField(null=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmer.Pengguna')),
            ],
        ),
        migrations.AlterField(
            model_name='data_pengajuan_lahan',
            name='tanggal_pengajuan',
            field=models.DateTimeField(null=True),
        ),
    ]
