# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-17 09:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0009_auto_20170517_0850'),
    ]

    operations = [
        migrations.AddField(
            model_name='data_pengajuan_peminjaman',
            name='no_rekening',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
