# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-18 03:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0011_auto_20170518_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_bibit_pupuk',
            name='jenis_komponen',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='data_bibit_pupuk',
            name='keterangan',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='data_bibit_pupuk',
            name='nama_komponen',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='data_kegiatan_pengolahan_lahan',
            name='keterangan',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='data_kegiatan_pengolahan_lahan',
            name='nama_kegiatan',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='data_kegiatan_pengolahan_lahan',
            name='status',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='data_kegiatan_pengolahan_lahan',
            name='tanggal_kegiatan',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='data_komposisi_lahan',
            name='jenis_komposisi',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='data_komposisi_lahan',
            name='keterangan',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='data_komposisi_lahan',
            name='nama_komposisi',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='data_lahan',
            name='alamat_lahan',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='data_lahan',
            name='keterangan',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='data_lahan',
            name='luas_lahan',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='data_lahan',
            name='tanggal_pengajuan',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='data_peminjaman',
            name='alasan_peminjaman',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='data_peminjaman',
            name='bank_name',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='data_peminjaman',
            name='besar_peminjaman',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='data_peminjaman',
            name='no_rekening',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='data_peminjaman',
            name='status',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='data_peminjaman',
            name='tanggal_peminjaman',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='data_pengajuan_lahan',
            name='alamat_lahan',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='data_pengajuan_lahan',
            name='alasan_penolakan',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='data_pengajuan_lahan',
            name='keterangan',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='data_pengajuan_lahan',
            name='luas_lahan',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='data_pengajuan_lahan',
            name='status',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='data_pengajuan_lahan',
            name='tanggal_pengajuan',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='data_pengajuan_peminjaman',
            name='alasan_peminjaman',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='data_pengajuan_peminjaman',
            name='alasan_penolakan',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='data_pengajuan_peminjaman',
            name='bank_name',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='data_pengajuan_peminjaman',
            name='besar_peminjaman',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='data_pengajuan_peminjaman',
            name='no_rekening',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='data_pengajuan_peminjaman',
            name='status',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='data_pengajuan_peminjaman',
            name='tanggal_peminjaman',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='pengguna',
            name='alamat',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='pengguna',
            name='full_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='pengguna',
            name='kabupaten',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='pengguna',
            name='kecamatan',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='pengguna',
            name='phone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='pengguna',
            name='username',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
