# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-19 01:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0012_auto_20170518_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='pengajuan_gambar_lahan',
            name='gambar',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
