# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-19 06:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0013_pengajuan_gambar_lahan_gambar'),
    ]

    operations = [
        migrations.AddField(
            model_name='data_gambar_lahan',
            name='gambar',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
