# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-23 04:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0014_data_gambar_lahan_gambar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data_kegiatan_pengolahan_lahan',
            old_name='tanggal_kegiatan',
            new_name='tanggal_mulai',
        ),
        migrations.AddField(
            model_name='data_kegiatan_pengolahan_lahan',
            name='tanggal_selesai',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
